# Generated by Django 5.2.7 on 2025-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_expense_description_remove_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Other', 'Other')], max_length=50),
        ),
    ]
